# Generated by Django 4.1.2 on 2022-11-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='Model')),
                ('sn', models.CharField(max_length=20, null=True, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='OS')),
                ('cpu', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=20, verbose_name='Memory')),
                ('hdd', models.CharField(blank=True, max_length=50, null=True, verbose_name='HDD')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('purchase_date', models.DateField(null=True, verbose_name='Purchase Date')),
                ('expire_date', models.DateField(null=True, verbose_name='Expire Date')),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Active')),
                ('is_container', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is Container')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(max_length=20, null=True, verbose_name='Create_by')),
                ('container', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itdc.asset', verbose_name='Container')),
            ],
            options={
                'db_table': 'itdc_all_asset',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Software Name')),
                ('softwarekey', models.CharField(max_length=150, verbose_name='Software Key')),
                ('quantity', models.SmallIntegerField(verbose_name='Quantity')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(default='', max_length=20, verbose_name='Create_by')),
                ('asset', models.ManyToManyField(to='itdc.asset', verbose_name='Asset')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.SmallIntegerField(verbose_name='Port Number')),
                ('connect_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connect To')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(default='', max_length=20, verbose_name='Create_by')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itdc.asset', verbose_name='Asset')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, null=True, verbose_name='Location')),
                ('address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(default='', max_length=20, verbose_name='Create_by')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itdc.asset', verbose_name='Asset')),
            ],
        ),
    ]
