# Generated by Django 4.1.2 on 2022-11-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Memory'),
        ),
    ]
