# Generated by Django 4.1.2 on 2022-11-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itdc', '0002_alter_asset_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_poweron',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Active'),
        ),
    ]
