# Generated by Django 4.1.2 on 2022-11-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itdc', '0003_asset_is_poweron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_poweron',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is PowerOn'),
        ),
    ]
