# Generated by Django 4.1.2 on 2022-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itdc', '0004_alter_asset_is_poweron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory'),
        ),
    ]
