# Generated by Django 4.0.8 on 2022-12-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itdc', '0005_alter_asset_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('create_by', models.CharField(max_length=20, verbose_name='Create By')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itdc.asset', verbose_name='Asset')),
            ],
        ),
    ]
