# Generated by Django 4.1.2 on 2022-10-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('folder', models.TextField(verbose_name='Folder')),
                ('lastwrite', models.DateTimeField(verbose_name='Last Write')),
                ('indexteime', models.DateTimeField(auto_now_add=True, verbose_name='Index Time')),
            ],
        ),
    ]
