# Generated by Django 4.1.2 on 2022-10-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_lastwrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Index Time')),
            ],
        ),
    ]
