# Generated by Django 4.1.2 on 2022-10-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_foldername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='indexteime',
            new_name='indextime',
        ),
    ]
