# Generated by Django 4.1.2 on 2022-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rootfolder',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Root Folder'),
        ),
    ]
