# Generated by Django 4.1.2 on 2022-10-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=20, unique=True, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=20, verbose_name='AssetName')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('purchase_date', models.DateField(default='', verbose_name='Purchase Date')),
                ('cpu', models.CharField(max_length=20, null=True, verbose_name='CPU')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(default='', max_length=20, verbose_name='Create_by')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='OSversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=20, unique=True, verbose_name='Acount')),
                ('name', models.CharField(max_length=20, verbose_name='User Name')),
                ('is_active', models.BooleanField(default=1, verbose_name='Status')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('create_by', models.CharField(default='', max_length=20, verbose_name='Create By')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.company', verbose_name='Company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.department', verbose_name='Department')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, verbose_name='Operator')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itasset.asset', verbose_name='Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.assetcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='hdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.hdd', verbose_name='HDD'),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.memory', verbose_name='Memory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.assetmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.officeversion', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.osversion', verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.assetstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itasset.vendor', verbose_name='Vendor'),
        ),
    ]
