# Generated by Django 4.1.1 on 2022-10-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0003_alter_asset_sn_alter_asset_status_alter_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistory',
            name='action',
            field=models.CharField(default='None', max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(default='None', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.CharField(max_length=20, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(default='None', max_length=20, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='create_by',
            field=models.CharField(default='None', max_length=20, verbose_name='Create_by'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hdd',
            field=models.CharField(default='None', max_length=20, verbose_name='HDD'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(default='None', max_length=20, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(default='None', max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(default='None', max_length=50, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(default='None', max_length=50, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(default='None', max_length=50, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='None', max_length=20, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='None', max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='None', max_length=20, verbose_name='Location'),
        ),
    ]
