# Generated by Django 4.1.1 on 2022-10-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0005_alter_asset_category_alter_asset_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='create_by',
            field=models.CharField(default='', max_length=20, verbose_name='Create_by'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hdd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HDD'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=20, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor'),
        ),
    ]
