# Generated by Django 4.1.1 on 2022-10-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0006_alter_asset_comment_alter_asset_cpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, verbose_name='Operator')),
                ('action', models.CharField(default='None', max_length=20, verbose_name='Action')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itasset.user', verbose_name='Asset')),
            ],
        ),
    ]
