# Generated by Django 4.1.1 on 2022-11-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0007_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetModel',
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.SmallIntegerField(default=1, verbose_name='Warranty'),
            preserve_default=False,
        ),
    ]
