# Generated by Django 4.1.1 on 2022-11-15 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0009_tanium_alter_asset_comment_alter_userhistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanium',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
    ]
