# Generated by Django 4.1.2 on 2022-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0010_tanium_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU'),
        ),
    ]
