# Generated by Django 4.1.2 on 2022-11-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0011_alter_asset_cpu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HDD',
            new_name='HardDisk',
        ),
    ]
