# Generated by Django 4.1.2 on 2022-12-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0012_rename_hdd_harddisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Memory'),
        ),
    ]
