# Generated by Django 4.0.8 on 2022-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0013_alter_asset_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='initial_os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Initial OS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
