# Generated by Django 4.0.8 on 2023-03-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0015_alter_asset_name_alter_tanium_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
    ]
